 /******************************************************************************
 *
 * Module: Ultrasonic
 *
 * File Name: ultrasonic.c
 *
 * Description: Source file for the Ultrasonic driver

 *******************************************************************************/
#include "ultrasonic.h"
#include "icu.h"
#include "gpio.h"
#include <util/delay.h>


uint8 g_edge=0;
uint16 g_time=0;
uint16 g_distance=0;


/*
 Description:
 This function is used to Initialize the ICU driver, Setup the ICU call back function and
 Setup the direction for the trigger pin as output pin through the GPIO driver.
 */
void Ultrasonic_init(void)
{
	ICU_ConfigType ICU_configurations;

	ICU_configurations.clock=F_CPU_8;
	ICU_configurations.edge=RAISING;

	GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORT,ULTRASONIC_TRIGGER_PIN,PIN_OUTPUT);
	ICU_setCallBack(Ultrasonic_edgeProcessing);

	ICU_init(&ICU_configurations);


}
/*
 Description:
Send the Trigger pulse to the ultrasonic.
  */
void Ultrasonic_Trigger(void)
{
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT,ULTRASONIC_TRIGGER_PIN,LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT,ULTRASONIC_TRIGGER_PIN,LOGIC_LOW);

}

/*
 Description:
 Send the trigger pulse by using Ultrasonic_Trigger function
 and the measurements by the ICU starts from this moment
 */

uint16 Ultrasonic_readDistance(void)

{
	Ultrasonic_Trigger();


	g_distance=(g_time * 0.0085)+1;

	return g_distance;

}


/*
 Description:
This is the call back function called by the ICU driver
This is used to calculate the high time (pulse time) generated by
the ultrasonic sensor.g_time
 */

void Ultrasonic_edgeProcessing(void)
{
	g_edge++;
	if(g_edge==1)
	{
		ICU_clearTimerValue();
		ICU_setEdgeDetectionType(FALLING);
	}

	else if(g_edge==2)
	{
		g_time=ICU_getInputCaptureValue();
		ICU_clearTimerValue();
		ICU_setEdgeDetectionType(RAISING);
		g_edge=0;
	}



}
