 /******************************************************************************
 *
 * Module: Ultrasonic
 *
 * File Name: ultrasonic.h
 *
 * Description: header file for the Ultrasonic driver

 *******************************************************************************/
#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#include "std_types.h"
#include "common_macros.h"

#define ULTRASONIC_TRIGGER_PORT   PORTB_ID
#define ULTRASONIC_TRIGGER_PIN    PIN5_ID

#define ULTRASONIC_ECHO_PORT      PORTD_ID
#define ULTRASONIC_ECHO_PIN       PIN6_ID

/*
 Description:
 This function is used to Initialize the ICU driver, Setup the ICU call back function and
 Setup the direction for the trigger pin as output pin through the GPIO driver.
 */

void Ultrasonic_init(void);

/*
 Description:
Send the Trigger pulse to the ultrasonic.
  */

void Ultrasonic_Trigger(void);

/*
 Description:
 Send the trigger pulse by using Ultrasonic_Trigger function
 and the measurements by the ICU starts from this moment
 */


uint16 Ultrasonic_readDistance(void);

/*
 Description:
This is the call back function called by the ICU driver
This is used to calculate the high time (pulse time) generated by
the ultrasonic sensor.
 */

void Ultrasonic_edgeProcessing(void);










#endif /* ULTRASONIC_H_ */
